### ISSUE TITLE
assets in scss file

### ISSUE THREAD

**Issue by Nemo64** [zendesk/app_scaffold#47]
I tried migrating an app from v1 and v2 and am basically done, this repo helped a lot.
However, I noticed that all images that are references via css do not work as soon as the app is properly installed.

I am not skilled with webpack but it is the problem here. I have to write image paths like `url("/image.png")` or else it can't resolve images within the dist folder. However, I get absolute urls in my app which won't work as soon as I upload them to zendesk (Which has the assets in a folder like `106609/assets/1483613068-fa78dc30432094d311a5bd1c056d5cba/`.

Could you give me a hint how to reference images within my stylesheet? Maybe adjust this scaffold so it works out of the box?

**Comment by danielbreves** [comment]
@Nemo64 glad to hear this has helped you. This was indeed a bug, thanks for reporting. We merged a fix, could you try it and let us know if it solves it for you please?

**Comment by adammw** [comment]
Hi @Nemo64 - I just updated the scaffold so that should now work out of the box. If you've already started migrating your app, you'll just need to update the `package.json` and `webpack.config.js` files and re-run `npm install`.

To reference images in your css, relative urls are preferred over absolute urls, for example in the app scaffold, there's now a `src/images/` folder for the spinner image that can be referred to in the css by `../images/spinner.gif`. Absolute urls should work now for assets in the `dist/assets` folder, however this is discouraged as webpack will attempt to overwrite these files each time you build, and they may get included twice if they are small enough to fit inside the css file as a data uri.

**Comment by Nemo64** [comment]
So it now uses base64 to include images. Actually not a bad idea, might safe a lot of small requests.
It works now thanks. ;)
