### ISSUE TITLE
Document example of how to handle UI events

### ISSUE THREAD

**Issue by cbrunnkvist** [zendesk/app_scaffold#89]
It would be nice to have an example in the bare scaffold of not only how to send data to the view, but also how the authors imagine binding UI events in the view and acting on them back in the controller. A simple "You clicked me" would do, I think, and newcomers could set off from there.

**Comment by yu-tian113** [comment]
Hi @cbrunnkvist, thanks very for the advice, we have published the new version scaffold with a completely rebuild. Please try out, any issues and contributions are welcome.

As a scaffold, our primary goal is to provide app developers with preconfigured development tooling, so they can focus on the app itself.
V2 apps live in their own iframes, app developers have completely freedom to choose the tools/frameworks they want to use to build their apps. That's why we remove pretty much all runtime dependencies from the new version scaffold, as we won't set any restrictions like how you should bind views to controller.

In the meantime, we'd love to help everyone needs any support while building apps, please feel free to post issues here, contribute, and follow https://developer.zendesk.com/, we'll upload new articles and tutorials to help out the community.
